config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  root to: 'pages#home'
 
 end 

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs["name"].blank? }

  include Placeholder
  validates_presence_of :title, :body
  extend FriendlyId
  friendly_id :title, use: :slugged

  def self.angular
    where(subtitle: "Angular")
  end

  scope :Ruby_on_Rails, lambda { where(subtitle: "Ruby on Rails") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height:600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height:350, width: 200)
  end
end 



 

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:edit, :update, :destroy, :show]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :edit, :new, :create, :update]}, site_admin: :all
  def index
    @portfolio_items = Portfolio.friendly.all
  end 

  def angular
    @angular_portfolio_items = Portfolio.friendly.angular
  end
  
  def new
    @portfolio_item = Portfolio.friendly.new
    3.times do @portfolio_item.technologies.build end 
  end

  def create
    @portfolio_item = Portfolio.friendly.new(portfolio_params)
     respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end 

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Record was successfully destroyed.' }
    end
  end 

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      technologies_attributes: [:name]
                                      )
  end 

  private

  def set_portfolio
    @portfolio_item = Portfolio.friendly.find(params[:id])
  end 

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technoloy_form| %>
    <li>
      <%= technoloy_form.label :name %>
      <%= technoloy_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
 <p> <%= link_to "Back", portfolios_path %> </p>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item)  %> </p>
<p> <%= portfolio_item.subtitle %> </p>
<p> <%= portfolio_item.body %> </p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?  %>
<p> <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> </p>
<p> <%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %> </p>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item)  %> </p>
  <p> <%= portfolio_item.subtitle %> </p>
  <p> <%= portfolio_item.body %> </p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?  %>
  <p> <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> </p>
  <p> <%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %> </p>
<% end %>
 

app/views/portfolios/edit.html.erb
<h1>Edit an existing Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= "#{@copyright}:)".html_safe %>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin)%> 

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

 

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>

<h1> <%= @portfolio_item.title %> </h1>

<em> <%= @portfolio_item.subtitle %> </em>

<p> <%= @portfolio_item.body %> </p>

<h2> Portfolio Technologies used: </h2>

<% @portfolio_item.technologies.each do |x| %>
  <p> <%= x.name %> </p>
  <% end %>
<p> <%= link_to 'Destroy', portfolio_path(@portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %> </p>
<p> <%= link_to "Edit", edit_portfolio_path(@portfolio_item) if logged_in?(:site_admin) %> </p>
<p> <%= link_to "Back", portfolios_path %> </p>