config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
    member do 
      get :toggle_status
    end 
  end
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  root to: 'pages#home'
 
 end 

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
  <p><%= copyright_generator %> </p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
      <h3 class="masthead-brand"><%= link_to "bencanwrite", root_path, class: "btn btn-danger" %></h3>
      <nav class="nav nav-masthead">
        <%= link_to 'home', root_path, class: 'nav-link' %>
        <%= link_to 'about me', about_me_path, class: 'nav-link' %>
        <%= link_to 'contact', contact_path, class: 'nav-link' %>
        <%= link_to 'blog', blogs_path, class: 'nav-link' %>
        <%= link_to 'portfolio', portfolios_path, class: 'nav-link' %>
        <%= login_helper 'nav-link' %>
      </nav>
  </div>
</div>        

app/views/shared/_nav.html.erb
<div class="<%= location %>">
<%= link_to 'home', root_path %>
<%= link_to 'about me', about_me_path %>
<%= link_to 'contact', contact_path %>
<%= link_to 'blog', blogs_path %>
<%= link_to 'portfolio', portfolios_path %>